image:
  repository: ghcr.io/keptn-sandbox/git-promotion-service
  tag: latest
pullPolicy: Always
externalUrl: ~

subscription:
  pubSubUrl: 'nats://keptn-nats'
  pubSubTopic: sh.keptn.event.git-promotion.>